services:
  auth-db:
    image: gvenzl/oracle-free:23-slim
    environment:
      ORACLE_PASSWORD: ${AUTH_ORACLE_PASSWORD}
      APP_USER: authuser
      APP_USER_PASSWORD: ${AUTH_DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
      start_interval: 5s
    volumes:
      - auth-oracle-data:/opt/oracle/oradata

  workspaces-db:
    image: gvenzl/oracle-free:23-slim
    environment:
      ORACLE_PASSWORD: ${WORKSPACES_ORACLE_PASSWORD}
      APP_USER: workspacesuser
      APP_USER_PASSWORD: ${WORKSPACES_DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
      start_interval: 5s
    volumes:
      - workspaces-oracle-data:/opt/oracle/oradata

  projects-db:
    image: gvenzl/oracle-free:23-slim
    environment:
      ORACLE_PASSWORD: ${PROJECTS_ORACLE_PASSWORD}
      APP_USER: projectsuser
      APP_USER_PASSWORD: ${PROJECTS_DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
      start_interval: 5s
    volumes:
      - projects-oracle-data:/opt/oracle/oradata

volumes:
  auth-oracle-data:
  workspaces-oracle-data:
  projects-oracle-data: