services:
  auth-db:
    image: gvenzl/oracle-free:23-slim
    container_name: devflow-auth-db
    ports:
      - "1522:1521"
    environment:
      ORACLE_PASSWORD: ${AUTH_ORACLE_PASSWORD}
      APP_USER: authuser
      APP_USER_PASSWORD: ${AUTH_DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
      start_interval: 5s
    volumes:
      - auth-oracle-data:/opt/oracle/oradata

  workspaces-db:
    image: gvenzl/oracle-free:23-slim
    container_name: devflow-workspaces-db
    ports:
      - "1523:1521"
    environment:
      ORACLE_PASSWORD: ${WORKSPACES_ORACLE_PASSWORD}
      APP_USER: workspacesuser
      APP_USER_PASSWORD: ${WORKSPACES_DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
      start_interval: 5s
    volumes:
      - workspaces-oracle-data:/opt/oracle/oradata

  projects-db:
    image: gvenzl/oracle-free:23-slim
    container_name: devflow-projects-db
    ports:
      - "1524:1521"
    environment:
      ORACLE_PASSWORD: ${PROJECTS_ORACLE_PASSWORD}
      APP_USER: projectsuser
      APP_USER_PASSWORD: ${PROJECTS_DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
      start_interval: 5s
    volumes:
      - projects-oracle-data:/opt/oracle/oradata

  auth-api:
    build:
      context: .
      dockerfile: DevFlow.Auth.Api/Dockerfile
    image: devflow/auth-api:local
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__AuthDb: "User Id=authuser;Password=${AUTH_DB_PASSWORD};Data Source=auth-db:1521/FREEPDB1;"
    ports:
      - "8081:8080"
    depends_on:
     auth-db:
       condition: service_healthy

volumes:
  auth-oracle-data:
  workspaces-oracle-data:
  projects-oracle-data:
